"""init schema

Revision ID: 045a0c9aa5c6
Revises: 
Create Date: 2026-02-19 23:15:28.319375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045a0c9aa5c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_especialidade',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('duracao_consulta_padrao', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_procedimento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('uf_crm', sa.String(length=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('ddd', sa.SmallInteger(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_tipo_especialidade', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('data_consulta', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_especialidade'], ['tipo_especialidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidade_medico',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADO', 'BLOQUEADO', name='status_disponibilidade_medico_enum', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico_especialidade',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_tipo_especialidade', sa.Integer(), nullable=False),
    sa.Column('duracao_consulta', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_especialidade'], ['tipo_especialidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico_procedimento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_tipo_procedimento', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_procedimento'], ['tipo_procedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedimento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_tipo_procedimento', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_procedimento'], ['tipo_procedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimento')
    op.drop_table('medico_procedimento')
    op.drop_table('medico_especialidade')
    op.drop_table('disponibilidade_medico')
    op.drop_table('consulta')
    op.drop_table('telefone')
    op.drop_table('paciente')
    op.drop_table('medico')
    op.drop_table('documento')
    op.drop_table('tipo_procedimento')
    op.drop_table('tipo_especialidade')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
