classDiagram
    class Pessoa {
        id: int
        nome: str
        data_nascimento: date
        sexo: str
        cpf: str
        email: str
    }

    class Medico {
        id: int
        crm: str
        uf_crm: str
        data_criacao: datetime
        data_inativacao: datetime
        id_pessoa: int
    }

    class DisponibilidadeMedico {
        id: int
        id_medico: int
        data_inicio: date
        data_fim: date
        hora_inicio: time
        hora_fim: time
        dia_semana: int
        status: StatusDisponibilidadeMedico
    }

    class TipoEspecialidade {
        id: int
        descricao: str
        duracao_consulta_padrao: int
        embedding: str
    }

    class MedicoEspecialidade {
        id: int
        id_medico: int
        id_tipo_especialidade: int
        duracao_consulta: int
        data_criacao: datetime
        data_inativacao: datetime
    }

    class Consulta {
        id: int
        id_funcionario: int
        id_paciente: int
        id_tipo_especialidade: int
        id_medico: int
        data_consulta: datetime
        observacao: str
        data_criacao: datetime
        data_inativacao: datetime
    }

    class TipoProcedimento {
        id: int
        descricao: str
        embedding: str
    }

    class Procedimento {
        id: int
        id_medico: int
        id_tipo_procedimento: int
        observacao: str
    }

    class MedicoProcedimento {
        id: int
        id_medico: int
        id_tipo_procedimento: int
        data: date
    }

    class Telefone {
        id: int
        id_pessoa: int
        numero: str
        ddd: int
        data_criacao: datetime
        data_inativacao: datetime
    }

    class Paciente {
        id_pessoa: int
        ativo: bool
    }

    class Documento {
        id: int
        id_tipo_documento: int
        id_pessoa: int
        numero: str
    }

    Pessoa "1" --> "0..1" Medico
    Pessoa "1" --> "0..1" Paciente
    Pessoa "1" --> "0..*" Telefone
    Pessoa "1" --> "0..*" Documento

    Medico "1" --> "0..*" Consulta
    Medico "1" --> "0..*" DisponibilidadeMedico
    Medico "1" --> "0..*" MedicoEspecialidade
    Medico "1" --> "0..*" MedicoProcedimento
    Medico "1" --> "0..*" Procedimento

    TipoEspecialidade "1" --> "0..*" Consulta
    TipoEspecialidade "1" --> "0..*" MedicoEspecialidade

    TipoProcedimento "1" --> "0..*" Procedimento
    TipoProcedimento "1" --> "0..*" MedicoProcedimento

    MedicoEspecialidade "*" --> "1" Medico
    MedicoEspecialidade "*" --> "1" TipoEspecialidade

    MedicoProcedimento "*" --> "1" Medico
    MedicoProcedimento "*" --> "1" TipoProcedimento

    Procedimento "*" --> "1" TipoProcedimento
    Procedimento "*" --> "0..1" Medico

    Telefone "*" --> "1" Pessoa
    Documento "*" --> "1" Pessoa
    Paciente "1" --> "1" Pessoa